- Services/TimetableManager.php
> Embedded type

- Tests/Functional/Controller/LayoutModelControllerTest.php
> Test updated.

- Resources/config/doctrine/AreaPdf.orm.yml
- Services/PdfGenCompletionLib.php
- Tests/Functional/Controller/LayoutModelControllerTest.php
> Configuration of area entity in yml updated for worker caching.

- Controller/PdfController.php
- Controller/TimetableController.php
- Resources/public/css/layouts.css
- Resources/public/css/main.css
- Resources/public/css/print.css
- Resources/views/Layouts/base_layout.html.twig
Needs a 'portrait' model to be tested
> Feature meth 479 portrait archive layout

- Resources/views/Layouts/macros.html.twig
- Resources/views/Layouts/timegrid.html.twig
Macro calendar evo to get right css classes for coloring lines or columns
> macro even/odd style on line or column

- Entity/StopPoint.php
- Services/Navitia.php
- Services/StopPointManager.php
To see city in Models / templates
> add city to stoppoint

- Twig/TaskTypeExtension.php
bad default case displaying always 'area' link
Landing page from a network
> hotfix-bad-season-pdfs-link

- Controller/AreaController.php
- Resources/config/routing.yml
- Resources/public/css/main.css
- Resources/translations/default.fr.yml
- Resources/views/Area/editStops.html.twig
- Resources/views/Area/list.html.twig
- Resources/views/Area/listPdf.html.twig
- Tests/Functional/Controller/AreaControllerTest.php
> changed area wording and added a button from list of pdfs

- Tests/Functional/Controller/AbstractControllerTest.php
It will be launched directly by Jenkins prior to test launch
> Remove database reset task

- Resources/translations/messages.fr.yml
- Resources/views/Season/form.html.twig
~~Waiting for PO validation~~
to see this,
go to Saisons > gestion des Saisons > Créer une saison
Ticket METH-498
> adding text in form

- Tests/DataFixtures/ORM/Fixture.php
- Tests/Functional/Controller/AreaControllerTest.php
> update broken tests

- Resources/public/css/main.css
- Resources/public/js/area.js
- Resources/views/Area/editStops.html.twig
METH-505
Hide a btn if useless
To test Secteurs > Choisir les arrêts
> hiding btn if useless

- Resources/views/StopPoint/list.html.twig
- Tests/Functional/Controller/TimetableControllerTest.php
Page 'Édition des fiches horaires'
Ticket METH-297 , btns for each stop-point
> edit btns action presence

- Resources/translations/messages.fr.yml
To replace #47
Minor test addition METH-498
> wording addition

- .gitignore
- composer.json
- phpunit.xml.dist
composer install
vendor/bin/phpunit
> run unit tests from the bundle

- Entity/Timetable.php
- Services/Navitia.php
- Services/TimetableManager.php
Adding city name to direction in Timetable
(model editino required)
REQUIRE : CanalTP/NmmPortalBundle#8
override #50
> Hotfix meth 540 city direction

- Controller/WebserviceController.php
Patch on 1.9
WS to obtain a pdf (already generated thru ihm)
Details in meth- 555 ticket.
Generate a pdf as a client, check if you can retrieve it
> Patchchanging canonical to identifier

- Resources/config/services.yml
- Services/Navitia.php
- Services/StopPointManager.php
Refactoring init stop point 
Instead of calling 3 times the same stop point request, we can do it once
> Refactoring init stop point

- Migrations/pdo_pgsql/Version012.php
@vpassama 
- I created the sequences automatically with SERIAL
- I put REFERENCES next to the field. This creates the foreign key automatically
> simplify sequence and foreign key creation

- Command/AckWorkerCommand.php
Seen with @vincentlepot and @datanel
> Ack worker should ack messages only if everything went well

- Services/LayoutModelManager.php
fixed BC break when uploading a layout model
Include upload/{layoutId} in the path
> Fix bad template path + checkstyle PSR2

- .gitignore
- Entity/LineTimetable.php
- Entity/StopTimetable.php
- Entity/StopTimetableRepository.php
- Entity/Timetable.php
- Resources/config/doctrine/LineConfig.orm.yml
- Resources/config/doctrine/LineTimetable.orm.yml
- Resources/config/doctrine/StopTimetable.orm.yml
- Services/PdfGenCompletionLib.php
- Services/StopTimetableManager.php
This PR adds a Timetable entity in order to manage common resources between stopTimetable and lineTimetable.
> Timetable entity

- Resources/views/Layouts/timegrid.html.twig
> Revert "Fix color notes by passing the notesType var to the schedule filter"

- PULL_REQUEST_TEMPLATE
Adding a Pull Request Template will help us to provide some minimal informations about what we bring to the product.
GitHub provides a help page to create a Pull Request template: https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/
> Add a first Pull Request Template draft

- Tests/DataFixtures/ORM/Fixture.php
- Tests/Functional/Controller/CalendarControllerTest.php
- Tests/Functional/Controller/DefaultControllerTest.php
This PR fixes tests
replaces https://github.com/CanalTP/MttBundle/pull/92
BUG
needs https://github.com/CanalTP/NMM/pull/168
- In app/config/config_test_mtt.yml, change the database parameters
- run ```./bin/run-tests-tt.sh```
> fixed tests with JDR

- Entity/Calendar.php
- Resources/config/doctrine/Calendar.orm.yml
Added  an entity Calendar
you can persist a calendar and get it from the database and see if everything is mapped correctly
```php
$em = $this->get('doctrine')->getManager();
$customer = $em->find('CanalTP\NmmPortalBundle\Entity\Customer', 1);
$calendar = new Calendar();
$calendar
->setTitle('title')
->setStartDate(new \DateTime())
->setEndDate(new \DateTime())
->setCustomer($customer)
->setWeeklyPattern('0000011')
;
$em->persist($calendar);
$em->flush();
$em->refresh($calendar);
dump($calendar);
```
> added entity for calendar

- Controller/CalendarController.php
- Form/Type/CalendarType.php
- Resources/translations/default.fr.yml
- Resources/views/Calendar/create.html.twig
- Tests/Functional/Controller/CalendarControllerTest.php
Create basic calendar form
New feature
go to http://{your_nmm_domain}/app_dev.php/mtt/calendars/create and enjoy the beautiful form
@tchevily @vchabot @dvdn @nberard
> created form calendar

- Entity/Calendar.php
- Resources/config/validation.yml
- Tests/Unit/Entity/CalendarTest.php
Adding validation for calendar Entity
new feature
Launch 
```
phpunit -c app/ vendor/canaltp/mtt-bundle/Tests/Unit/Entity/CalendarTest.php
```
@djerrah @datanel
> Adding validation for start and end dates for calendar entity

- Controller/CalendarController.php
- Entity/Calendar.php
- Form/Type/CalendarType.php
- Resources/config/validation.yml
- Resources/translations/default.fr.yml
- Resources/translations/messages.fr.yml
- Tests/Functional/Controller/CalendarControllerTest.php
- Tests/Unit/Entity/CalendarTest.php
Submit and persist a calendar
new feature
- Run the tests
- go to http://{your_nmm_domain}/app_dev.php/mtt/calendars/create, fill the form and validate 
@tchevily @vchabot @dvdn @nberard
> Submit form calendar

- installation.md
i add some detail for the configuration
back office team
> more detail for the configuration

- installation.md
console line break
Mention here the people who should review your PR
back office team
> console line break

- installation.md
> launch amqpmttworker

- Calendar/CalendarArchiveGenerator.php
- Calendar/GridCalendarsCsv.php
- Calendar/GridNetworksAndLinesCsv.php
- Calendar/GridPeriodsCsv.php
- Controller/CalendarController.php
- CsvGenerator.php
- CsvModelInterface.php
- Entity/Calendar.php
- Entity/CalendarRepository.php
- Resources/config/doctrine/Calendar.orm.yml
- Resources/config/routing.yml
- Resources/translations/default.fr.yml
- Resources/views/Calendar/list.html.twig
- Tests/DataFixtures/ORM/Fixture.php
- Tests/Functional/Controller/CalendarControllerTest.php
- Tests/Unit/Calendar/CalendarArchiveGeneratorTest.php
- Tests/Unit/CsvGeneratorTest.php
- Twig/ScheduleExtension.php
- composer.json
needs https://github.com/CanalTP/NmmPortalBundle/pull/24
This PR add the export of calendars with a zip containing 2 csv (grid_calendars.csv and grid_periods.csv)
new feature
In the bundle
```
composer update
./vendor/bin/phpunit
```
In Timetable go to /mtt/calendars/list, create calendars and click to export button
@alcalyn @asfram
> Export calendar

- Controller/CalendarController.php
- Resources/config/routing.yml
- Resources/translations/default.fr.yml
- Resources/translations/exceptions.fr.yml
- Resources/views/Calendar/edit.html.twig
- Resources/views/Calendar/list.html.twig
- Tests/Functional/Controller/CalendarControllerTest.php
This PR adds an edit action on a calendar in the calendars list
http://jira.canaltp.fr/browse/HOR-3
This is a  new feature
Team Schedule
> Feature hor 3 edit calendar

- CsvGenerator.php
- Tests/Unit/CsvGeneratorTest.php
use , instead of ; as csv delimiter
> use , instead of ; as csv delimiter

- Controller/CalendarController.php
- Resources/config/routing.yml
- Resources/config/services.yml
- Resources/translations/default.fr.yml
- Resources/translations/messages.fr.yml
- Resources/views/Calendar/list.html.twig
- Tests/Functional/Controller/CalendarControllerTest.php
I add delete button to remove a calendar
This is  new feature
run this feature with this command 
./bin/run-test-tt.sh
@datanel @asfram
> Feature delete button

- Controller/CalendarController.php
- Resources/translations/default.fr.yml
- Resources/views/Calendar/create.html.twig
- Resources/views/Calendar/edit.html.twig
- Tests/Functional/Controller/CalendarControllerTest.php
Back button
#Team reviewer 
@datanel @asfram
> i add back button for create calendar page

- Services/Navitia.php
- composer.json
needs canaltp/navitia:1.3.0
This PR fixes stop_schedules call
> fixed stop_schedules calls

- Services/Navitia.php
- Tests/DataFixtures/ORM/Fixture.php
- Twig/ScheduleExtension.php
- composer.json
needs canaltp/navitia:1.3.0
This PR fixes stop_schedules call
> fixes stop_schedules call

- Calendar/CalendarExport.php
- Controller/CalendarController.php
- Resources/config/services.yml
- Tests/Unit/Calendar/CalendarExportTest.php
- composer.json
needs https://github.com/CanalTP/NMM/pull/215
This is a  new feature
- Start the tartare web service
- Export calendars in Timetable and see if you receive a message OK from tartare
> post calendar zip to tartare

- Calendar/GridCalendarsCsv.php
- Calendar/GridPeriodsCsv.php
- Tests/Unit/Calendar/GridCalendarsCsvTest.php
- Tests/Unit/Calendar/GridPeriodsCsvTest.php
Changed some headers
- grid_calendar_id => id
- start_date => begin_date
_grid_calendar_id => calendar_id
> fixed calendars headers

- Form/Type/CalendarType.php
- Resources/config/validation.yml
- Resources/translations/default.fr.yml
- Resources/translations/messages.fr.yml
- Resources/views/Calendar/create.html.twig
- Resources/views/Calendar/edit.html.twig
- Resources/views/Calendar/form.html.twig
- Tests/Functional/Controller/CalendarControllerTest.php
Select days of week instead of writing "0100011"
This is a new feature?
go to /mtt/calendars/create
> [Calendar] changed weekly pattern to checkboxes

- installation.md
This PR remove bridge bundle reference
> remove bridge reference

- composer.json
Fix version of willdurand/js-translation-bundle
This is a fix
> allow upgrade of js-translation-bundle

- Tests/Functional/Controller/SeasonControllerTest.php
> Set fixed datetime for test

- Services/Amqp/PdfPayloadsGenerator.php
This PR fix the problem with the pdf generation pages sizes when launch with the rabbitMq
Issue link: BOT-125
⚠️ Need https://github.com/CanalTP/AmqpMttWorkers/pull/5 to see the result
> Send page size for pdf generator

- Controller/LayoutModelController.php
This PR Fix the problem with opcache on updated template
Issue link: __BOT-176__
- Try to upload a new version of an existing template 
- Check if it work
> Reset opcache when upload existing template

- composer.json
This PR update the requirement version of boostrap to the last 3.*
Issue link: BOT-2132
> [Boostrap] Update version

- composer.json
> Revert "[Boostrap] Update version"
