- Entity/StopPoint.php
- Resources/views/Calendar/view.html.twig
- Resources/views/Layouts/default.html.twig
- Resources/views/Layouts/macros.html.twig
- Services/CalendarManager.php
- Services/Navitia.php
- Services/StopPointManager.php
- Tests/Functional/Controller/TimetableControllerTest.php
- Tests/Unit/Twig/StopPointExtensionTest.php
- Twig/StopPointExtension.php
Tests depending on https://github.com/datanel/SamCoreBundle/pull/1
We have now the possibility to display the stop point code we want, not the external code.
if navitia returns 
```json
stop_points": [{    
"codes": [
{    
"type": "code_tata",
"value": "bobette"
},
{
"type": "code_toto",
"value": "bob"
},
{    
"type": "totem",
"value": "654895"
},    
{   
"type": "external_code",
"value": "AFG2568"
}
],
"name": "Arrêt A",
....
}], 
```
for a stop point, we can specify that we want for example the "totem" code
How to do that?
Each layout can call a twig macro that display the code.
```html
{{ macros.stop_point_code('text_block_4', stopPoint, 'small-block', 'Code TOTEM de cet arrêt') }}
```
We can now pass another parameter corresponding to the type in the response.
```html
{{ …
```
> Specify the stop point code to display

- Controller/CustomerController.php
- Controller/LayoutConfigController.php
- Controller/LayoutModelController.php
- Resources/config/routing.yml
- Resources/translations/default.fr.yml
- Resources/translations/messages.fr.yml
- Resources/views/Customer/list.html.twig
- Resources/views/LayoutModel/list.html.twig
- Services/LayoutManager.php
- Tests/Functional/Controller/LayoutModelControllerTest.php
related to https://github.com/CanalTP/MttBridgeBundle/pull/5
The former page "Gestion des clients" is splitted in 2 pages
- "Ajout/Mettre à jour les modèles" which contains: 
- the button "Ajouter un modèle" 
- List of models with the upload date
- "Assigner les modèles aux clients" which contains : 
- A list of customers with perimeters and assigned models
> New assign page

- Controller/WebserviceController.php
[findSeasionByCustomerAndDate](https://github.com/CanalTP/MttBundle/commit/e37fc387a15b8f73c0833f2dfe93e053b0ab4991#commitcomment-12976633) renamed to findSeasonByCustomerAndDate
[Useless line removed](https://github.com/CanalTP/MttBundle/blame/master/Controller/WebserviceController.php#L65)
Thanks @VincentCATILLON and @jbcrestot
> Typo correction

- Controller/LineTimetableController.php
- Resources/config/routing.yml
- Resources/public/css/main.css
- Resources/translations/default.fr.yml
- Resources/translations/messages.fr.yml
- Resources/views/Layouts/macros.html.twig
- Resources/views/LineTimetable/list.html.twig
- Resources/views/LineTimetable/schedule.html.twig
- Services/CalendarManager.php
- Services/Navitia.php
- Tests/Unit/Services/CalendarManagerTest.php
This PR contains the preview page for a LineTimetable schedules data and is related to the issue https://github.com/CanalTP/MttBundle/issues/61.
I'll edit the presentation soon. For the moment, the feature is not finished.
> Adding schedule preview page for LineTimetable.

- Services/Amqp/PdfPayloadsGenerator.php
- Services/PdfManager.php
In order to simplify NMM configuration, the aim of this PR is to act with a null value for payload_host as if it is not specified at all.
> Manage null payload host param

- Controller/CustomerController.php
- Controller/LayoutConfigController.php
- Controller/LayoutModelController.php
- DataFixtures/ORM/FixturesRole.php
- Resources/config/permissions.yml
- Resources/translations/messages.fr.yml
related to https://github.com/CanalTP/MttBridgeBundle/pull/10
An admin can list/add/edit a layout model and assign those models to a customer
And a user can now list/add/edit/delete a layout configuration.
So there are 3 permissions : 
- BUSINESS_MANAGE_MODEL (list/add/edit a layout model)
- BUSINESS_ASSIGN_MODEL (assign thoses models to a customer)
- BUSINESS_MANAGE_LAYOUT_CONFIG ( list/add/edit/delete a layout configuration)
Changelog:
- Renamed BUSINESS_MANAGE_CUSTOMER (deprecated) to BUSINESS_ASSIGN_MODEL
- Added BUSINESS_MANAGE_MODEL
- Removed BUSINESS_LIST_LAYOUT_CONFIG (deprecated)
In NMM as super administrator you have to change the permissions 
- deselect **Gestion des modèles de fond de fiche** and **Assignation de modèles aux clients** to a **user MTT**
- select everything for …
> Changed Some permissions

- Services/CalendarManager.php
- Tests/Unit/Services/CalendarManagerTest.php
- composer.json
when cloning a season with obsolete calendars there is the following error
Navitia error message: Filters: Unable to find object (500 Internal Server Error) 
The first step to fix this is to catch the exception and let the cloning continue so we do not display the error anymore.
> catch and not display navitia errors when cloning a season

- Entity/Layout.php
- Migrations/pdo_pgsql/Version012.php
- Resources/config/doctrine/Layout.orm.yml
- Services/LayoutModelManager.php
- Tests/Unit/Entity/LayoutTest.php
- Rename Layout.php test class in LayoutTest.php
- Add paperSize property to the Layout entity
- Add a migration
- Add test to cover the setPaperSize method.
- Added mapping doctrine
- In NMM run ```php app/console claroline:migration:upgrade CanalTPMttBundle --target=farthest```
- Import a layout: 
- Without page_size attribute: default value should be A4 in the "layout" table, field "page_size"
- With page_size attribute in a3, A3, a4, A4, a5, A5, : field "page_size" should be the specified one
- With invalid page_size (eg: "A8"): You should not see the layout in the list page (the error message is not displayed because there is a identified bug)
> Add pageSize property to the Layout entity

- Services/PdfGenerator.php
- Services/PdfManager.php
Add page-size parameter to the PdfGenerator and to the PdfManager.
- Add a layout with the `pageSize` parameter to "A4", add it to a client and configure it to generate a PDF. The generated PDF must have the "A4" format.
- Add a layout without the `pageSize` parameter, add it to a client and configure it to generate a PDF. The generated PDF must have the "A4" format.
- Add a layout with the `pageSize` parameter to "A3", add it to a client and configure it to generate a PDF. The generated PDF must have the "A3" format.
> Add page-size parameter to the PdfGenerator and PdfManager

- Resources/views/Layouts/timegrid.html.twig
The timegrid template was ignoring the notesType var when calling the schedule filter, which was an issue when trying to color a note on a calendar.
> Fix color notes by passing the notesType var to the schedule filter

- Resources/public/css/main.css
- Tests/Unit/Twig/ScheduleExtensionTest.php
- Twig/ScheduleExtension.php
For coloring all td cell when note type color selected
ergonomic contribution
configure a 'fiche horaire' 
- select note type couleur
- got to 'previsualisation' and check result
before : column 0h
this PR : column 23h
> Calendar / color note / colorize all the cell

- Services/Navitia.php
This PR fixes the bug where in staging environment, Navitia POI types "point of sale" were not found, because there is a difference between the prod env and the staging envs.
- Preview a FH and see that POI are found and visible in the FH.
@datanel / @djerrah / @tchevily 
This change will make work the POI in staging envs and not in prod anymore for now. We should see how we can fix this for every environments.
> Change navitia poi_type from Pointsdevente to point_of_sale

- Services/Navitia.php
This PR reverts the previous one, #109 because networks already use this naming and the new networks will use this naming instead of changing everything.
> Revert poi_type naming to Pointsdevente instead of point_of_sale

- Twig/TaskTypeExtension.php
This PR fixes a PHP fatal error in PHP 7:
`PHP Fatal error:  Switch statements may only contain one default clause in vendor/canaltp/mtt-bundle/Twig/TaskTypeExtension.php on line 109`
The test suite will be enough to test this PR
> Fix PHP Lint error with switch and double default

- Migrations/pdo_pgsql/Version013.php
Create calendar table with following fields
- id (serial primary not null)
- title (varchar not null)
- start_date (datetime not null)
- end_date (dateteime not null)
- week_pattern (char(7) eg: 0010010)
- customer_id (integer not null)
new feature
`php app/console claroline:migration:upgrade CanalTPMttBundle --target=farthest`
`php app/console claroline:migration:downgrade CanalTPMttBundle`
> added migration for calendar

- Controller/CalendarController.php
- Controller/DefaultController.php
- Resources/config/routing.yml
- Resources/translations/default.fr.yml
- Resources/views/Calendar/create.html.twig
- Tests/Functional/Controller/AbstractControllerTest.php
- Tests/Functional/Controller/CalendarControllerTest.php
This PR adds the createAction method in CalendarController, with the associated routing and twig file.
This is a new feature
You can go to http://{your_nmm_url}/mtt/networks/network:BIBUS/calendars/create and you will see the title `Création d'un calendrier`.
@datanel @dvdn @djerrah @nberard
> Initialize create action in Calendars controller

- composer.json
This PR fixes unit tests. 
As unit tests are run from the bundle, symfony/validator was missing in composer.json
Bugfix
In the bundle
```
composer update
./vendor/bin/phpunit
```
@tchevily @vchabot @dvdn @nberard
> missing validator

- Form/Type/CalendarType.php
removed a placeholder for weekly pattern
This is a bug fix / new feature?
enhancement
go to http://{nmm_domain}}/calendars/create and see if the placeholder of weekly pattern input is removed
> [Calendar form] removed placeholder for weekly pattern

- Services/Amqp/Channel.php
- composer.json
videlalvaro/php-amqplib has changed to php-amqplib/php-amqplib
- **PhpAmqpLib\Connection\AMQPConnection** is deprecated. We have to use **PhpAmqpLib\Connection\AMQPStreamConnection**
- The namespaces are the same so it's totally Backward compatible
`composer require canaltp/mtt-bundle:dev-fix-deprecated-amqplib --update-with-dependencies`
> Fix deprecated amqplib

- Controller/CalendarController.php
- Resources/config/routing.yml
- Resources/translations/default.fr.yml
- Resources/translations/messages.fr.yml
- Resources/views/Calendar/list.html.twig
- Tests/Functional/Controller/CalendarControllerTest.php
This PR adds list of calendars
Issue link: METH-639
This is a new feature
- Connect as Mtt user.
- Menu item "calendriers" should appear
- On click on this item, you are redirected to the page of calendars list
- You can see the "Liste des calendriers" as page title
This PR depends on https://github.com/CanalTP/MttBridgeBundle/pull/15
@datanel @kun2985 @dvdn @nberard
> Adding calendar list action/view

- Controller/CalendarController.php
- PULL_REQUEST_TEMPLATE
- Resources/config/routing.yml
- Resources/config/services.yml
- Resources/translations/default.fr.yml
- Resources/translations/messages.fr.yml
- Resources/views/Calendar/list.html.twig
- Tests/Functional/Controller/CalendarControllerTest.php
- Tests/Unit/Twig/CalendarExtensionTest.php
- Twig/CalendarExtension.php
This PR displays list of calendars in List page of calendar controller
Issue link: METH-639
This is a new feature
- Log as Mtt user
- Click on "calendriers" menu item
- List of available calendars appears
- Calendar create button is visible
~~This PR depends on https://github.com/CanalTP/MttBundle/pull/126~~ merged
@datanel @kun2985 @dvdn @nberard 
Update functional test
> Feature meth 639 calendar list with data

- Calendar/GridNetworksAndLinesCsv.php
- Controller/CalendarController.php
- CsvGenerator.php
- Tests/Unit/Calendar/CalendarTrait.php
- Tests/Unit/Calendar/CustomerTrait.php
- Tests/Unit/Calendar/GridCalendarsTest.php
- Tests/Unit/Calendar/GridNetworksAndLinesCsvTest.php
- Tests/Unit/Calendar/GridPeriodsCsvTest.php
- Tests/Unit/CsvGeneratorTest.php
- composer.json
Fixed grid_rel_calendar_to_network_and_line.txt
A customer should only export calendars on their networks
- CustomerA has coverage covX with networks networkA1 and networkA2 and 1 calendars A1 and A2
- CustomerB has coverage covX with networks networkB1 and calendar calendar B1
grid_rel_calendar_to_network_and_line.txt sould be
```
grid_calendar_id,network_id,line_code
A1,network:A1,
A1,network:A2,
A2,network:A1,
A2,network:A2,
B1,network:B1,
```
> fixed csv grid_rel_calendar_to_network_and_line.txt

- Calendar/GridNetworksAndLinesCsv.php
- Entity/CalendarRepository.php
fixed grid_rel_calendar_to_network_and_line.txt
- CustomerA has 
- coverage covX with networks networkA1 and networkA2 and 1 calendars A1 and A2
- coverage covY with networks networkA3
- CustomerB has 
- coverage covX with networks networkB1 and calendar calendar B1
grid_rel_calendar_to_network_and_line.txt sould be
```
grid_calendar_id,network_id,line_code
A1,network:A1,
A1,network:A2,
A2,network:A1,
A2,network:A2,
B1,network:B1,
```
> fixed csv calendars with networks

- Calendar/CalendarExport.php
- Tests/Unit/Calendar/CalendarExportTest.php
Tartare now needs to know the coverage when exporting a calendar
The api has changed and is now /coverages/{coverage_id}/grid_calendar
This is an enhancement
> added coverage to export call

- Form/Handler/Block/ImgHandler.php
- Services/BlockTypeFactory.php
Save a png with an extension in lowercase just to not have a .PNG and .png files with the same name.
Edit an image block.
1. Choose an image with `.png` extension
2. Choose an image with `.PNG` extension
3. Choose an image with `.png` extension
You have to see the images in the block
> force extension png in lowercase

- Entity/Layout.php
Fix Fatal Error with php7 Layout::__toString must return a string value when uploading a layout model
requires php7
Upload a model
> Fix Fatal Error with php7 Layout::__toString must return a string value

- Resources/config/validation.yml
Fix PHP Fatal error:  Cannot use 'True' as class name as it is reserved in path/to/vendor/symfony/validator/Constraints/True.php on line 24
This is a bug fix for php7
you need php7
```
composer install 
./vendor/bin/phpunit
```
@guilde_nmm
> Fix True is reserved word in php7

- composer.json
This PR fixes the unit test failing due to the release of Twig 2.0.
This is a test fix
- Checkout mttbundle alone
- composer install with php >=5.6
- launch unit tests
NMM guilde
> Fix twig constraint in composer (not compatible with twig 2)

- composer.json
Change name of guzzle package in composer.json to be able to install guzzle >=5.0 (guzzlehttp/guzzle": "~5.0") and upgrade easily
This is a fix
> changed name of guzzle package

- Resources/views/Layouts/base_layout.html.twig
- Resources/views/base.html.twig
This PR fix error when generating pdf timetable when GTM is enable
Set GTM then try to generate a pdf of a timetable
@CanalTP/transteam
> Check param timetableOnly in url for disable GTM

- Tests/Functional/Controller/AbstractControllerTest.php
This PR fixes a test fail if IP of the mock client is not mocked (hence 127.0.0.1)
This is a test fix
- Nothing changed at software level
- The build must be green 
NMM Guilde
> Fix test to avoid IP exception in security.yml

- Services/LayoutManager.php
When you manage models (only admins role allowed) it's useless time consuming to scroll to the end of sometimes looong models list.
Sorting by created date assures that what's fresh is in first position of the list. No more scroll.
Check your models list /mtt/layouts/networks/network:[abc-xyz]/model/list
lasts created models are on top
> Stop scrolling to new models

- composer.json
All monitoring services in services.yml need canaltp/sam-monitoring-bundle
fix https://jira.canaltp.fr/browse/GN-26
> Added dependency to canaltp/sam-monitoring-bundle

- Migrations/pdo_pgsql/Version014.php
This PR updates constraints in order to delete a customer and his perimeters swiftly
Issue link: BOT-451
https://github.com/CanalTP/NMM/issues/341
- launch `php app/console claroline:migration:upgrade CanalTPMttBundle --target=farthest` in order to update the mtt schema
- try to delete some related data
> Update constraints to delete on cascade

- Resources/config/routing.yml
This PR fix the routing error access from NMM
relates to https://github.com/CanalTP/SamCoreBundle/pull/69
Issue link: BOT-2137
- In NMM, connect with a user that have mtt access
- Go with the upper left menu on the mtt app
- You should see the dashboard of mtt
> Add default route for mtt
